include: package:surf_lint_rules/analysis_options.yaml

analyzer:
  exclude:
    - "**/generated/**"
    - "**/l10n/**"
    - "**/*.config.dart"
    - "**/generated_plugin_registrant.dart"
    - "**/*.g.dart"
    - "**/*.gr.dart"
